server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coffeenotes}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: coffeenotes
  flyway:
    enabled: true
    schemas: coffeenotes
    default-schema: coffeenotes

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG


app:
  security:
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS:http://localhost:3000}
    jwt:
      issuer: ${APP_SECURITY_JWT_ISSUER:coffeenotes-api}
      audience: ${APP_SECURITY_JWT_AUDIENCE:coffeenotes-web}
      private-key-location: ${APP_SECURITY_JWT_PRIVATE_KEY_LOCATION:file:../secrets/private_key.pem}
      public-key-location: ${APP_SECURITY_JWT_PUBLIC_KEY_LOCATION:file:../secrets/public_key.pem}
    cookie:
      secure: ${APP_SECURITY_COOKIE_SECURE:true}
      same-site: ${APP_SECURITY_COOKIE_SAME_SITE:Lax}
